# Capstone 2: Obesity in America
## Preprocessing and Training Data Development

The goal of this step is to create a cleaned development dataset to be used for the modeling step. 

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn import linear_model, preprocessing
from sklearn.preprocessing import MinMaxScaler

In [7]:
cd data

/Users/erinquense/springboard/Capstone2Project/data


In [8]:
df = pd.read_csv('df_for_preprocess.csv', index_col=0)

In [9]:
df.head()

Year Location  % who have obesity Total  18 - 24  25 - 34  35 - 44  \
0  2011-01-01   Alaska                19.8     0        1        0        0   
1  2011-01-01   Alaska                23.5     0        0        1        0   
2  2011-01-01   Alaska                29.5     0        0        0        1   
3  2011-01-01   Alaska                29.2     0        0        0        0   
4  2011-01-01   Alaska                33.4     0        0        0        0   

   45 - 54  55 - 64  65 or older  ...  Non-Hispanic White  Other  \
0        0        0            0  ...                   0      0   
1        0        0            0  ...                   0      0   
2        0        0            0  ...                   0      0   
3        1        0            0  ...                   0      0   
4        0        1            0  ...                   0      0   

   B_% who are overweight  B_% who are moderately active  \
0                     Low                      Very High   
1               Very High                      Very High   
2               Very High                           High   
3               Very High                      Very High   
4               Very High                      Very High   

   B_% who are moderately active and strength train  \
0                                         Very High   
1                                         Very High   
2                                              High   
3                                         Very High   
4                                              High   

   B_% who are vigorously after  B_% who strength train  \
0                          High               Very High   
1                     Very High               Very High   
2                          High                    High   
3                     Very High                    High   
4                     Very High                  Medium   

   B_% who no physical activity  B_% less than 1 vegetable/day  \
0                           Low                      Very High   
1                           Low                            Low   
2                        Medium                            Low   
3                        Medium                            Low   
4                          High                            Low   

   B_% less than 1 fruit/day  
0                  Very High  
1                       High  
2                       High  
3                     Medium  
4                        Low  

[5 rows x 39 columns]

In [10]:
df = df.drop(['Year'], axis=1)

Convert categorical features to numerical using dummy variables.

In [11]:
dummy = pd.get_dummies(df['Location'])
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['Location'], axis=1)

In [12]:
dummy = pd.get_dummies(df['B_% who are overweight'], prefix='overweight_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who are overweight'], axis=1)

In [13]:
dummy = pd.get_dummies(df['B_% who are moderately active'], prefix='mod_active_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who are moderately active'], axis=1)

In [14]:
dummy = pd.get_dummies(df['B_% who are moderately active and strength train'], prefix='mod_and_strength_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who are moderately active and strength train'], axis=1)

In [15]:
dummy = pd.get_dummies(df['B_% who are vigorously after'], prefix='vigor_active_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who are vigorously after'], axis=1)

In [16]:
dummy = pd.get_dummies(df['B_% who strength train'], prefix='strength_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who strength train'], axis=1)

In [17]:
dummy = pd.get_dummies(df['B_% who no physical activity'], prefix='no_PA_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% who no physical activity'], axis=1)

In [18]:
dummy = pd.get_dummies(df['B_% less than 1 vegetable/day'], prefix='vege_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% less than 1 vegetable/day'], axis=1)

In [19]:
dummy = pd.get_dummies(df['B_% less than 1 fruit/day'], prefix='fruit_')
df = pd.concat([df, dummy], axis = 1)
df = df.drop(['B_% less than 1 fruit/day'], axis=1)

In [20]:
df = df.drop(['Total'], axis=1)

In [21]:
df.head()

% who have obesity  18 - 24  25 - 34  35 - 44  45 - 54  55 - 64  \
0                19.8        1        0        0        0        0   
1                23.5        0        1        0        0        0   
2                29.5        0        0        1        0        0   
3                29.2        0        0        0        1        0   
4                33.4        0        0        0        0        1   

   65 or older  College graduate  High school graduate  Less than high school  \
0            0                 0                     0                      0   
1            0                 0                     0                      0   
2            0                 0                     0                      0   
3            0                 0                     0                      0   
4            0                 0                     0                      0   

   ...  vege__Medium  vege__No Data Reported  vege__Very High  vege__Very Low  \
0  ...             0                       0                1               0   
1  ...             0                       0                0               0   
2  ...             0                       0                0               0   
3  ...             0                       0                0               0   
4  ...             0                       0                0               0   

   fruit__High  fruit__Low  fruit__Medium  fruit__No Data Reported  \
0            0           0              0                        0   
1            1           0              0                        0   
2            1           0              0                        0   
3            0           0              1                        0   
4            0           1              0                        0   

   fruit__Very High  fruit__Very Low  
0                 1                0  
1                 0                0  
2                 0                0  
3                 0                0  
4                 0                0  

[5 rows x 131 columns]

In [22]:
df.to_csv('df_for_model_fitting.csv')

## Linear Regression
### Model 1

In [56]:
X = df.drop(['% who have obesity'], axis=1).values
y = df['% who have obesity'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)

In [59]:
print("X_train: ", type(X_train), X_train.shape)
print("y_train: ", type(y_train), y_train.shape)
print("X_test: ", type(X_test), X_test.shape)
print("y_test: ", type(y_test), y_test.shape)

X_train:  <class 'numpy.ndarray'> (6114, 130)
y_train:  <class 'numpy.ndarray'> (6114,)
X_test:  <class 'numpy.ndarray'> (2039, 130)
y_test:  <class 'numpy.ndarray'> (2039,)


In [62]:
y_train = y_train.reshape(-1, 1)
y_test = y_test.reshape(-1, 1)

Standardize the value of numeric features- in this case, % who have obesity is the only numeric feature that needs to be scaled.  I will use the MinMax Scaler to scale it between 0 and 1. 

In [63]:
MM_scaler = MinMaxScaler()
MM_scaler.fit(y_test)
y_test = MM_scaler.transform(y_test)

In [64]:
MM_scaler.fit(y_train)
y_train = MM_scaler.transform(y_train)

In [66]:
print("\n")
print("X_train:", X_train, type(X_train), X_train.shape, len(X_train)) #TrainX

print("\n")
print("X_test", X_test, type(X_test), X_test.shape, len(X_test)) #TestX

print("\n")
print("y_train", y_train, type(y_train), y_train.shape, len(y_train)) #Trainy

print("\n")
print("y_test", y_test, type(y_test), y_test.shape, len(y_test)) #Testy



X_train: [[0 0 0 ... 0 1 0]
 [0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]] <class 'numpy.ndarray'> (6114, 130) 6114


X_test [[0 0 0 ... 1 0 0]
 [0 0 1 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]] <class 'numpy.ndarray'> (2039, 130) 2039


y_train [[0.52773109]
 [0.54957983]
 [0.46722689]
 ...
 [0.38487395]
 [0.45546218]
 [0.41176471]] <class 'numpy.ndarray'> (6114, 1) 6114


y_test [[0.28089888]
 [0.52247191]
 [0.66104869]
 ...
 [0.50749064]
 [0.29026217]
 [0.37827715]] <class 'numpy.ndarray'> (2039, 1) 2039


In [75]:
rModel = linear_model.LinearRegression(normalize=True)

In [76]:
rModel.fit(X_train, y_train)

LinearRegression(normalize=True)

In [100]:
y_predict_test = rModel.predict(X_test)
MM_scaler.fit(y_predict_test)
y_predict_test = MM_scaler.transform(y_predict_test)
print("Test Mean Absolute Error:",mean_absolute_error(y_test, y_predict_test))

y_predict_training = rModel.predict(X_train)
MM_scaler.fit(y_predict_training)
y_predict_training = MM_scaler.transform(y_predict_training)
print("Train Mean Absolute Error:",mean_absolute_error(y_train, y_predict_training))

Test Mean Absolute Error: 0.49575613847216093
Train Mean Absolute Error: 0.1416791273761677


In [104]:
y_predict_test = rModel.predict(X_test)
MM_scaler.fit(y_predict_test)
y_predict_test = MM_scaler.transform(y_predict_test)
print("Test RSquared:", rModel.score(X_test, y_predict_test))

y_predict_training = rModel.predict(X_train)
MM_scaler.fit(y_predict_training)
y_predict_training = MM_scaler.transform(y_predict_training)
print("Training RSquared:", rModel.score(X_train, y_predict_training))

Test RSquared: -4.435014933527908e+21
Training RSquared: -0.21802503876438428
